### ISSUE TITLE
YouTube video link in README.md is broken

### ISSUE THREAD

**Issue by JanneKiiskila** [AVSystem/Anjay-freertos-client#1]
The video link in the `README.md` is not pointing to a working video file.

https://www.youtube.com/watchv=fgy38XfttM8

gives 404.

**Comment by Mierunski** [comment]
Hi!
Thanks for the heads up, there is a typo, `?` is missing, proper link: https://www.youtube.com/watch?v=fgy38XfttM8
We will fix it in the next release, contributions are also welcome

**Comment by JanneKiiskila** [comment]
https://github.com/AVSystem/Anjay-freertos-client/pull/2 raised.

**Comment by Mierunski** [comment]
Fixed by #2
