### ISSUE TITLE
Anjay-freertos-client 21.10 showing error when build with STM32 CubeIDE

### ISSUE THREAD

**Issue by Goyalvij** [AVSystem/Anjay-freertos-client#3]
Hi Team,
Is Anjay-freertos-client 21.10 buildable?
We having error when we build it with STM32 cube IDE.

Please support us or share the buildable code.
We are using STM32CubeIde Version: 1.8.0.

Regards,
Vijendra

**Comment by Mierunski** [comment]
Hi!
Could you share the error message?
If you build for L462 please remember to use Release build

Best regards,
Mieszko

**Comment by Goyalvij** [comment]
Hi,
We having below errors

14:09:41 **** Build of configuration Release for project Anjay-freertos-client-B-L462E-CELL1-TYPE1SC ****
make -j8 all 
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/accelerometer_driver.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/accelerometer_driver.d" -MT"app_compat/accelerometer_driver.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/accelerometer_driver.o"
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/barometer_driver.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/barometer_driver.d" -MT"app_compat/barometer_driver.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/barometer_driver.o"
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/config_persistence.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/config_persistence.d" -MT"app_compat/config_persistence.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/config_persistence.o"
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/gyrometer_driver.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/gyrometer_driver.d" -MT"app_compat/gyrometer_driver.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/gyrometer_driver.o"
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/hygrometer_driver.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/hygrometer_driver.d" -MT"app_compat/hygrometer_driver.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/hygrometer_driver.o"
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/magnetometer_driver.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/magnetometer_driver.d" -MT"app_compat/magnetometer_driver.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/magnetometer_driver.o"
arm-none-eabi-gcc "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/thermometer_driver.c" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L462xx -DUSE_SOCKETS_TYPE=USE_SOCKETS_LWIP '-DMBEDTLS_CONFIG_FILE="mbedtls.h"' -DUSE_B_L462E_CELL1 -c -I../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/include_public -I../../../../Middlewares/Third_Party/Anjay/src -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/include_public -I../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../Middlewares/Third_Party/Anjay/deps/avs_coap/src -I../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../Middlewares/Third_Party/Anjay/include_public -I../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../Middlewares/Third_Party/LwIP/system -I../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../Middlewares/Third_Party/mbedtls/include -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../Middlewares/Third_Party/Anjay/deps/avs_commons/src -I../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../Application/Inc -I../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../Inc -I../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/TYPE1SC/AT_modem_type1sc/Inc -I../../../../Drivers/BSP/Components/ssd1315 -I../../../../Drivers/BSP/Components/Common -I../../../../Drivers/BSP/Components/hts221 -I../../../../Drivers/BSP/Components/lps22hh -I../../../../Drivers/BSP/Components/lsm303agr -I../../../../Utilities/Fonts -I../../../../Drivers/BSP/B-L462E-CELL1 -I../../../../Application/Inc/plf -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"app_compat/thermometer_driver.d" -MT"app_compat/thermometer_driver.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "app_compat/thermometer_driver.o"
arm-none-eabi-gcc -mcpu=cortex-m4 -c -x assembler-with-cpp -MMD -MP -MF"Startup/startup_stm32l462reyx.d" -MT"Startup/startup_stm32l462reyx.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "Startup/startup_stm32l462reyx.o" "C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/Startup/startup_stm32l462reyx.s"
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/accelerometer_driver.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/barometer_driver.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [app_compat/subdir.mk:37: app_compat/accelerometer_driver.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [app_compat/subdir.mk:39: app_compat/barometer_driver.o] Error 1
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/gyrometer_driver.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/config_persistence.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [app_compat/subdir.mk:43: app_compat/gyrometer_driver.o] Error 1
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/magnetometer_driver.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [app_compat/subdir.mk:41: app_compat/config_persistence.o] Error 1
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/hygrometer_driver.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [app_compat/subdir.mk:47: app_compat/magnetometer_driver.o] Error 1
make: *** [app_compat/subdir.mk:45: app_compat/hygrometer_driver.o] Error 1
C:/Users/44137/Desktop/Anjay-freertos-client-21.10/Anjay-freertos-client-21.10/Projects/B-L462E-CELL1/app_compat/thermometer_driver.c:17:10: fatal error: avsystem/commons/avs_log.h: No such file or directory
   17 | #include <avsystem/commons/avs_log.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [app_compat/subdir.mk:49: app_compat/thermometer_driver.o] Error 1
"make -j8 all" terminated with exit code 2. Build might be incomplete.

14:09:44 Build Failed. 15 errors, 0 warnings. (took 2s.532ms)

Regards,
Vijendra

**Comment by Goyalvij** [comment]
Hi
Earlier I have downloaded the zip directly from the link and getting error in build.
Now I have git clone from 
git clone --recursive https://github.com/AVSystem/Anjay-freertos-client
This code have been successfully build.

Now we are looking for port source code from stm32l462e to stm32f411ce.
As my device is on stmm32f411ce.

Please suggest what approach should I follow for this.
Thanks in advance.

Regards,
Vijendra

**Comment by Mierunski** [comment]
Hi
Glad to hear that it worked, could you close this issue in that case?
For porting I'd recommend using I-CUBE-Anjay package - https://github.com/AVSystem/I-CUBE-Anjay and devzone tutorials https://iotdevzone.avsystem.com/docs/Anjay_integrations/Anjay_ST_integration/Building_LwM2M_applications/Building_LwM2M_applications_with_I-CUBE-Anjay/

For more support visit our Discord https://discord.avsystem.com/ were we can answer your questions faster

Best regards,
Mieszko
