### ISSUE TITLE
Can we use Keil with anjay?

### ISSUE THREAD

**Issue by Goyalvij** [AVSystem/Anjay-freertos-client#4]
Hello Team,
Is there any source code compile with KEIL IDE?

Regards,
Vijendra

**Comment by Mierunski** [comment]
Hi
Please take a look at https://github.com/AVSystem/I-CUBE-Anjay
After you install package using CubeMX, head to package folder and there you will find projects directory containing sample projects for Keil

Best regards,
Mieszko
