### ISSUE TITLE
Secure Boot ve Firmware Update for STM32U585

### ISSUE THREAD

**Issue by gencay3535** [AVSystem/Anjay-freertos-client#6]
Hello, I wanted to ask if secure boot and firmware update supported for the STM32U585?

**Comment by Mierunski** [comment]
Hi,
Currently it is supported in AzureRTOS integration https://github.com/AVSystem/Anjay-stm32-azurertos-client
Does that help?

BR
Mieszko

**Comment by gencay3535** [comment]
> Hi, Currently it is supported in AzureRTOS integration https://github.com/AVSystem/Anjay-stm32-azurertos-client Does that help?
> 
> BR Mieszko

Yes it does, thank you.
